/**
 * This file content is autogenerated at contract deployment.
 * You should not edit it manually or your changes might be overwritten.
 */

export const attensysCourseAddress =
  "0x57252fdaeb79acead9e2cebbca2f297dc6f9185095d19d7bf69317fe843c868";
export const attensysEventAddress =
  "0x22a82b2f66266eb28571af87a0cafa114bff1085912b549b94c3d6f47876b43";
export const attensysOrgAddress =
  "0x513294282e8430a4615345617304e82a0b8bf573de9cc79c1fbfb34a90440e3";
